name: auto_clean-Commits
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 1 * * 0,2,4,6"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  
    - name: Set up Git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name GitHub
        git config user.email noreply@github.com
        git reset --hard 8b65ea6

