name: auto_clean-Commits
on:
  push:
    branches: main
  workflow_dispatch:
  
  issues: 
    types: ["opened", "edited", "deleted", "labeled", "unlabeled"]
    
  schedule: 
    - cron: "0 1 * * 0,2,4,6"
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  
    - name: Set up Git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name GitHub
        git config user.email noreply@github.com
        git reset --hard HEAD~1
    - name: Commit and push changes
      run: |
        git add .
        if output=$(git status --porcelain) && [ ! -z "$output" ]; then
          git commit --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" --message "update the goals cache"
          git push
        fi
