name: Code Quality

on:
  workflow_dispatch:

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest
      - name: Reset October modules and library
        run: |
          git reset --hard HEAD
